# Generated by Django 4.2 on 2026-04-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_article_content_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
