# Generated by Django 4.2 on 2026-04-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('A', 'Hola'), ('B', 'NoaH')], help_text='Enter your title', max_length=100),
        ),
    ]
