# Generated by Django 4.2 on 2026-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('Hola', 'Hola'), ('NoaH', 'NoaH'), ('Casa', 'Casa')], default='A', help_text='Enter your title', max_length=100),
        ),
    ]
