# Generated by Django 4.2 on 2026-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Hola', 'Hola'), ('NoaH', 'NoaH'), ('Casa', 'Casa')], default='Casa', max_length=100),
        ),
    ]
