# Generated by Django 4.2 on 2026-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter your title', max_length=100),
        ),
    ]
