# Generated by Django 4.2 on 2026-04-20 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 10, 33, 40, 391409, tzinfo=datetime.timezone.utc)),
        ),
    ]
