# Generated by Django 4.2 on 2026-04-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_remove_article_category_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 10, 40, 35, 743710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter your title', max_length=100, unique_for_date='pub_date'),
        ),
    ]
