# Generated by Django 4.2 on 2026-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0012_category_remove_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
