# Generated by Django 4.2 on 2026-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_alter_category_options_article_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='files/article'),
        ),
    ]
