# Generated by Django 4.2 on 2026-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0014_alter_article_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='postimage',
            field=models.ImageField(null=True, upload_to='images/article'),
        ),
    ]
