# Generated by Django 4.2 on 2026-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0015_article_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/article'),
        ),
    ]
