# Generated by Django 4.2 on 2026-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0017_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
