# Generated by Django 4.2 on 2026-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0022_article_slug_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/article'),
        ),
    ]
