# Generated by Django 5.0.14 on 2026-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(default='images/social.png', upload_to='images/social'),
        ),
    ]
