# Generated by Django 5.0.14 on 2026-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_social_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(default='images/social.png', upload_to='images/social'),
        ),
    ]
